### ISSUE TITLE
MehtapKarakuşCV

### ISSUE THREAD

**Issue by somnambol** [tugbasuzek/2015ProjectGroup#1]
[CV.pdf](https://github.com/tugbasuzek/2015ProjectGroup/files/60125/CV.pdf)

**Comment by tugbasuzek** [comment]
[MehtapCV.pdf](https://github.com/tugbasuzek/2015ProjectGroup/files/60200/MehtapCV.pdf)

**Comment by somnambol** [comment]
[MehtapKarakuş_CV.pdf](https://github.com/tugbasuzek/2015ProjectGroup/files/66924/MehtapKarakus_CV.pdf)

**Comment by tugbasuzek** [comment]
Please just fix the typo "Visual" not visial. 
Otherwise looks good, thanks!
